### PR TITLE
set factor and column in CholmodNotPositiveDefiniteError in cholesky

### PR DESCRIPTION
**Pull request by jor-**
The values ``factor`` and ``column`` in the ``CholmodNotPositiveDefiniteError`` exception are not set if this exception is raised. I added some lines to do this.

(Due to the new error handling the error is already recognized in ``cholmod_factorize_p`` so the inspection of ``self._common._common.status`` is not needed anymore.)

### CODE REVIEW

**Comment by anntzer** [comment]
Clearly you are using this library more than me these days :-)  (See also #15, #16.)
Any interests in getting commit rights and taking care of it yourself?

**Comment by jor-** [comment]
Yes, commit rights would be nice. Especially, the integration of such small changes would then be easier.

**Comment by anntzer** [comment]
You should have received an invite now.  Have fun :)

**Comment by jor-** [comment]
Yes, I am now a scikit-sparse member. :-)
It would be nice if you grant me write access.

**Comment by anntzer** [comment]
Oops.  Should be done now.

**Comment by jor-** [comment]
Thank you. It is working now.

**Pull request merged**
