### PR TITLE
Add guide for installation with Windows and Anaconda

### PR DESCRIPTION
**Pull request by EmJay276**
There was no guide for Windows and I had a hard time figuring out how to install the package with Anaconda 3 (Python 3.7).
The solution is quiet simple by adding the anaconda paths to suitesparse include and library in the setup.py.

### CODE REVIEW

**Comment by batterseapower** [comment]
Thanks for this. The instructions still work with the latest conda/scikit-sparse though you need to make a trivial change to modify the new `INCLUDE_DIRS` and `LIBRARY_DIRS` variables in `setup.py` rather than the `setup` arguments directly.

**Comment by batterseapower** [comment]
Or I guess you can maybe use the new feature in #71 to set the paths.

**Comment by EmJay276** [comment]
I will have a look at it and change it.

**Comment by EmJay276** [comment]
@batterseapower I updated my guide by using the new features `SUITESPARSE_INCLUDE_DIR` and `SUITESPARSE_LIBRARY_DIR`

**Pull request merged**
