### PR TITLE
NumPy 1.13 support

### PR DESCRIPTION
**Pull request by jor-**
I added NumPy 1.13 to Travis and the docs.

### CODE REVIEW

**Comment by anntzer** [comment]
Feel free to selfmerge this when the tests pass.
I would also suggest just testing numpy 1.8.0 and numpy 1.13.0 (and possibly drop py3.5 as you have both 3.4 and 3.6) otherwise the number of test cases start being a bit ridiculous.  Not that it's really an issue for now though.

**Comment by jor-** [comment]
I thought about merging such small changes directly. But I think a PR is a good way to keep interested people like you up-to-date and of course get some feedback.

I also thought about dropping some test configurations. But I would prefer to drop the oldest versions (NumPy 1.8 and maybe 1.9 and Python 3.4). So the most recent versions are always tested and guaranteed to work.

**Comment by anntzer** [comment]
I certainly appreciate the pr, my point was just that I had looked at it before all the tests passed but I had no doubt that they would 😃
I think it makes more sense to test the first and last supported versions of everything, so perhaps I would add the oldest and newest scipy as well.  But it's up to you.

**Comment by jor-** [comment]
Using the first and last supported version does not guarantee that the intermediate versions work without errors. I have now used the last two versions of NumPy, Scipy and Python3 and Python2.7 for the tests. In general, older versions will work too. However, if problems occur in older versions, a more recent version must be used.

**Pull request merged**
