### PR TITLE
fix for numpy 1.12

### PR DESCRIPTION
**Pull request by anntzer**
@grlee77 please check this works for you.
@jor- can you review this (specifically the second commit)?

### CODE REVIEW

**Comment by jor-** [comment]
It looks good to me. Thanks for the quick fix.

**Comment by anntzer** [comment]
@jor- can you take care of updating the docs and releasing a new version?

**Comment by grlee77** [comment]
yes,  this fixes the problem.  thanks!

**Comment by jor-** [comment]
Okay, I am going to update the docs and make a new release tomorrow.

**Pull request merged**
